### ISSUE TITLE
Idea-Have a option that the chat log can go to a file in the console

### ISSUE THREAD

**Issue by brexmania123** [kenygamer/ChatLogger#2]
#### Description
Hi so i know that you could always just use the command but i would like to have it so i could always just go to a file on the console that shows the times and what the players say. Thank you for listening

#### Versions

* PocketMine Version: 3.0.0-Alpha11
* ChatLogger Version: 1.0.0-beta
* Game Version: PE / Windows 10 1.2.10

#### Crashdump or console errors

N/A

**Comment by kenygamer** [comment]
Thanks for your suggestion! I might consider adding it.

**Comment by kenygamer** [comment]
Sorry, but I don't have plans to do something like that. The links could be, however, shortened in the future. For now, you will have to go to the full URL:
```
https://chatlogger.herokuapp.com/?id=YourReportID
```
